# shellcheck shell=bash
#
# Shared helpers for the Claudezilla installers.
#
# install-macos.sh and install-linux.sh differ only in their platform paths and
# the extra Linux steps (headless profile, systemd unit); the host wrapper,
# native manifest, and MCP dependency install were duplicated line-for-line.
# They live here so a change to any of them happens once.

# Resolve an absolute node path. GUI-launched Firefox does not inherit the
# user's shell PATH, so the wrapper cannot rely on PATH lookup at launch.
clz_require_node() {
    local node
    node="$(command -v node 2>/dev/null)"
    if [ -z "$node" ]; then
        echo "Error: node not found in PATH. Please install Node.js first." >&2
        return 1
    fi
    printf '%s\n' "$node"
}

# clz_write_wrapper <wrapper-path> <entry-filename> <node-path>
#
# Writes the launcher that Firefox and Claude Code execute. It keeps the
# absolute node path (GUI-launched Firefox does not inherit the user's PATH)
# but resolves the checkout from its own location rather than hardcoding it,
# so moving or copying the checkout does not leave a launcher pointing at the
# old path. <entry-filename> is relative to the wrapper's own directory.
clz_write_wrapper() {
    local wrapper_path="$1" entry="$2" node_path="$3"

    cat > "$wrapper_path" << WRAPPER_EOF
#!/bin/bash
# Generated by the Claudezilla installer — do not edit.

CLZ_NODE="$node_path"
CLZ_ENTRY="$entry"
WRAPPER_EOF

    # Quoted heredoc: this half must reach the wrapper verbatim.
    cat >> "$wrapper_path" << 'WRAPPER_EOF'

# Resolve this script's real directory, following symlinks.
self="${BASH_SOURCE[0]}"
while [ -L "$self" ]; do
    target="$(readlink "$self")"
    case "$target" in
        /*) self="$target" ;;
        *)  self="$(dirname "$self")/$target" ;;
    esac
done
dir="$(cd "$(dirname "$self")" && pwd)"

exec "$CLZ_NODE" "$dir/$CLZ_ENTRY" "$@"
WRAPPER_EOF

    chmod 755 "$wrapper_path"
}

# clz_write_manifest <native-hosts-dir> <wrapper-path>
#
# Writes the native messaging manifest into a browser's hosts directory.
# SECURITY: manifest permissions are set explicitly.
clz_write_manifest() {
    local hosts_dir="$1" wrapper_path="$2"

    mkdir -p "$hosts_dir"
    cat > "$hosts_dir/claudezilla.json" << MANIFEST_EOF
{
  "name": "claudezilla",
  "description": "Claude Code Firefox browser automation bridge",
  "path": "$wrapper_path",
  "type": "stdio",
  "allowed_extensions": ["claudezilla@boot.industries"]
}
MANIFEST_EOF
    chmod 644 "$hosts_dir/claudezilla.json"
}

# clz_install_mcp_deps <mcp-dir>
clz_install_mcp_deps() {
    local mcp_dir="$1"

    if ! command -v npm >/dev/null 2>&1; then
        echo "Error: npm not found. Please install Node.js and npm first." >&2
        return 1
    fi
    echo "Installing MCP dependencies..."
    (cd "$mcp_dir" && npm install --quiet --ignore-scripts)
}
