# shellcheck shell=bash
#
# Shared helpers for the Claudezilla installers.
#
# Runtime policy: use Bun when it is installed, otherwise Node.js. Neither is
# required at install time beyond "at least one of them is present" — the
# generated wrappers repeat the same detection at launch, so installing or
# removing Bun later does not require re-running the installer.
#
# Everything the installer writes is relocatable: the wrappers resolve their
# own directory rather than baking in the checkout path.

# Locate a JavaScript runtime, preferring Bun. GUI-launched Firefox and the
# Claude Code desktop app do not inherit the user's shell PATH, so PATH lookup
# alone is not enough. Honours $CLZ_RUNTIME (explicit override), $BUN_INSTALL.
clz_find_runtime() {
    local candidate
    for candidate in \
        "${CLZ_RUNTIME:-}" \
        "${BUN_INSTALL:+$BUN_INSTALL/bin/bun}" \
        "$(command -v bun 2>/dev/null)" \
        "$HOME/.bun/bin/bun" \
        "/opt/homebrew/bin/bun" \
        "/usr/local/bin/bun" \
        "/usr/bin/bun" \
        "$(command -v node 2>/dev/null)" \
        "/opt/homebrew/bin/node" \
        "/usr/local/bin/node" \
        "/usr/bin/node"
    do
        if [ -n "$candidate" ] && [ -x "$candidate" ]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

clz_require_runtime() {
    local runtime
    if ! runtime="$(clz_find_runtime)"; then
        echo "Error: no JavaScript runtime found — install Bun or Node.js 18+." >&2
        echo "       Bun:     curl -fsSL https://bun.sh/install | bash" >&2
        echo "       Node.js: https://nodejs.org/" >&2
        echo "       Or set CLZ_RUNTIME=/path/to/runtime and re-run this installer." >&2
        return 1
    fi
    printf '%s\n' "$runtime"
}

# clz_write_manifest <native-hosts-dir> <wrapper-path>
#
# Writes the native messaging manifest into one browser's hosts directory.
clz_write_manifest() {
    local hosts_dir="$1" wrapper_path="$2"

    mkdir -p "$hosts_dir"
    cat > "$hosts_dir/claudezilla.json" << MANIFEST_EOF
{
  "name": "claudezilla",
  "description": "Claude Code Firefox browser automation bridge",
  "path": "$wrapper_path",
  "type": "stdio",
  "allowed_extensions": ["claudezilla@boot.industries"]
}
MANIFEST_EOF
    chmod 644 "$hosts_dir/claudezilla.json"
}

# clz_write_wrapper <wrapper-path> <entry-filename> <runtime-path>
#
# Writes a launcher that Firefox / Claude Code execute directly. The wrapper
# resolves its own directory (following symlinks) instead of baking in an
# absolute checkout path, and re-runs runtime detection at launch with the
# install-time choice tried first.
clz_write_wrapper() {
    local wrapper_path="$1" entry="$2" runtime_path="$3"

    cat > "$wrapper_path" << WRAPPER_EOF
#!/bin/bash
# Generated by the Claudezilla installer — do not edit.
# Launches $entry under Bun when available, otherwise Node.js, resolving both
# the checkout and the runtime at launch so the install survives a moved
# checkout, an upgraded runtime, or Bun being installed/removed later.

CLZ_RUNTIME_DEFAULT="$runtime_path"
CLZ_ENTRY="$entry"
WRAPPER_EOF

    # Quoted heredoc: this half must reach the wrapper verbatim.
    cat >> "$wrapper_path" << 'WRAPPER_EOF'

# Resolve this script's real directory, following symlinks.
self="${BASH_SOURCE[0]}"
while [ -L "$self" ]; do
    target="$(readlink "$self")"
    case "$target" in
        /*) self="$target" ;;
        *)  self="$(dirname "$self")/$target" ;;
    esac
done
dir="$(cd "$(dirname "$self")" && pwd)"

runtime=""
for candidate in \
    "${CLZ_RUNTIME:-}" \
    "$CLZ_RUNTIME_DEFAULT" \
    "${BUN_INSTALL:+$BUN_INSTALL/bin/bun}" \
    "$(command -v bun 2>/dev/null)" \
    "$HOME/.bun/bin/bun" \
    "/opt/homebrew/bin/bun" \
    "/usr/local/bin/bun" \
    "/usr/bin/bun" \
    "$(command -v node 2>/dev/null)" \
    "/opt/homebrew/bin/node" \
    "/usr/local/bin/node" \
    "/usr/bin/node"
do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        runtime="$candidate"
        break
    fi
done

if [ -z "$runtime" ]; then
    echo "claudezilla: no JavaScript runtime found — install Bun or Node.js, or set \$CLZ_RUNTIME" >&2
    exit 1
fi

exec "$runtime" "$dir/$CLZ_ENTRY" "$@"
WRAPPER_EOF

    chmod 755 "$wrapper_path"
}

# clz_install_mcp_deps <mcp-dir>
#
# Installs the MCP server's dependencies, preferring Bun when present.
#
# Bun leaves the committed package-lock.json untouched (it writes its own
# bun.lock, which is gitignored), so package-lock.json stays canonical for the
# Nix build regardless of which package manager the user ends up running.
clz_install_mcp_deps() {
    local mcp_dir="$1" bun

    bun="$(command -v bun 2>/dev/null || true)"
    if [ -n "$bun" ] && [ -x "$bun" ]; then
        echo "Installing MCP dependencies with Bun..."
        (cd "$mcp_dir" && "$bun" install --ignore-scripts)
        return
    fi

    if command -v npm >/dev/null 2>&1; then
        echo "Installing MCP dependencies with npm..."
        (cd "$mcp_dir" && npm install --quiet --ignore-scripts)
        return
    fi

    echo "Error: neither bun nor npm found — cannot install MCP dependencies." >&2
    return 1
}
